Make more portable
I installed timeout from homebrew, which is not in a standard path. This
was failing when run from shells that didn't have that path in their
PATH. Make this more portable.

diff --git a/add_line_to_today b/add_line_to_today
--- a/add_line_to_today
+++ b/add_line_to_today
@@ -13,6 +13,18 @@ get_filename() {
 
 stream_small_amount_of_data_into_todays_entry() {
   >&2 echo "INFO: Waiting at most one second for input."
+  case "$(uname -s)" in
+    Darwin)
+      /usr/local/opt/coreutils/libexec/gnubin/timeout 1 cat /dev/stdin >> "$(get_filename)"
+      ;;
+    Linux)
+      timeout 1 cat /dev/stdin >> "$(get_filename)"
+      ;;
+    *)
+      >&2 echo "Failed to find timeout."
+      exit 1
+      ;;
+  esac
   timeout 1 cat /dev/stdin >> "$(get_filename)"
   if [ $? -eq 124 ]
   then
